server:
  port: 8088
  tomcat:
    connection-timeout: 5s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: chap04-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/parandol/cloud-native-spring-in-action/chap04-config-repo
          default-label: main
