server:
  port: 9001
  tomcat:
    connection-timeout: 5s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8088
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false       # true 일 경우 config server에 접속할수 없으면 시작 시 종료. false면 retry 시도 후 내부 기본값 사용
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

management:
  endpoints:
    web:
      exposure:
        include: refresh

polar:
  greeting: Welcome to the local book catalog!
