server:
  port: 9001
  tomcat:
    connection-timeout: 5s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: chap04-catalog-service

polar:
  greeting: Welcome to the local book catalog!
