# curl -i http://httpbin.org/ip


POST http://localhost:9001/books
Content-Type: application/json

{
  "author": "Author",
  "title": "Northern",
  "isbn" : "12312BAS31",
  "price" : 10.99
}

###
GET http://localhost:9001/books
Content-Type: application/json